id: P008057
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:30.744527
source_metadata:
  id: bdr:W2PD16798
  title: ཆུ་ཆེན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    68acabfad80c440cb0248ef85a3de188:
      image_group_id: I2PD16802
      title: Volume 1 of chu chen rdzong gi sa cha'i ming btus/
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
