id: P008057
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD16798
  title: ཆུ་ཆེན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    7023f33207f943bf9453949055aba725:
      image_group_id: I2PD16802
      title: ''
      volume_number: 1
      total_pages: 234
ebook_metadata:
  title: ཆུ་ཆེན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  sku: P008057
  cover: cover.jpg
  layers:
  - pagination
